### ISSUE TITLE
Does not compile on 10.10

### ISSUE THREAD

**Issue by samoht** [dsheets/ocaml-osx-cf#3]
```
$ make
CTYPES_LIB_DIR=/Users/thomas/.opam/system/lib/ctypes OCAML_LIB_DIR=/usr/local/lib/ocaml ocamlbuild -use-ocamlfind -classic-display cf.cma cf.cmxa libcf_stubs.a dllcf_stubs.so cf_lwt.cma cf_lwt.cmxa
ocamlfind ocamlc -g -ccopt -I/usr/local/include -g -c lib/osx_cf_util.c
+ ocamlfind ocamlc -g -ccopt -I/usr/local/include -g -c lib/osx_cf_util.c
lib/osx_cf_util.c:11:1: error: unknown type name 'CFRunLoopRunResult'
CFRunLoopRunResult osx_cf_run_loop_run_in_mode
^
lib/osx_cf_util.c:13:21: error: expected ';' after expression
  CFRunLoopRunResult r;
                    ^
                    ;
lib/osx_cf_util.c:13:3: error: use of undeclared identifier 'CFRunLoopRunResult'
  CFRunLoopRunResult r;
  ^
lib/osx_cf_util.c:13:22: error: use of undeclared identifier 'r'
  CFRunLoopRunResult r;
                     ^
lib/osx_cf_util.c:15:3: error: use of undeclared identifier 'r'
  r = CFRunLoopRunInMode(mode, seconds, returnAfterSourceHandled);
  ^
lib/osx_cf_util.c:17:10: error: use of undeclared identifier 'r'
  return r;
         ^
6 errors generated.
Command exited with code 2.
make: *** [build] Error 10
```

It seems that `CFRunLoopRunResult` has been [added](https://developer.apple.com/library/mac/releasenotes/General/APIDiffsMacOSX10_11/Swift/CoreFoundation.html) in 10.11.
